### ISSUE TITLE
Add lambda:InvokeFunction in IAMRoleStatement

### ISSUE THREAD

**Issue by keitakn** [keitakn/serverless-aws-log-notifier#5]
## Done
- Added lambda:InvokeFunction in IAMRoleStatement.

**Comment by keitakn** [comment]
```
      Resource:
        - Fn::Join:
          - ":"
          - - arn:aws:lambda
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - function:${self:service}-${opt:stage, self:provider.stage}-*
```
